### PR TITLE
Fixes for Silktide Feb 2023 findings

### LINKED ISSUE #339: Silktide Feb 2023 findings
- [ ] Custom Search component's for on label and id on input are not displaying correctly
- [ ] No meaningful colour contrast for footer links focus state
- [ ] Insufficient colour contrast for Latest news sort by
- [ ] Insufficient colour contrast for pagination focus state
- [ ] Header logo North theme insufficient contrast on hover state
- [ ] Section links with image (Country parks page) insufficient pixels changing when focused

### PR DESCRIPTION
**Pull request by chrisrhymes**
Silktide has reported some potential issues with the Custom Search component and the focus states not having high enough contrast for several components. This is part of the WCAG 2.2 guidelines which are scheduled to be released in April this year. 

The main change is to keep a 2px focus colour border (previously 3px), but then add a 2px black border around the focus border to provide greater contrast to the white background. The change has been applied to the default `linkStylesFocus` from the theme, then applied manually where needed elsewhere. 

This is difficult to test as the Axe Dev tools only test the current rules, but here is some additional guidance (currently in draft): https://www.w3.org/WAI/WCAG22/Understanding/focus-appearance-minimum

Fixes #339

### CODE REVIEW

File: .storybook/preview.js [hunk 1]
```diff
@@ -45,7 +45,7 @@ export const globalTypes = {
     toolbar: {
       icon: 'circlehollow',
       items: ['north_theme', 'west_theme', 'lb_theme_north', 'lb_theme_west'],
-      showName: true,
+      title: 'Theme',
```
Comment (chrisrhymes) [inline .storybook/preview.js:48]: This gets rid of a console warning for Storybook abut deprecated behaviour.

File: src/library/components/CustomSearch/CustomSearch.stories.tsx [hunk 2]
```diff
@@ -26,3 +26,6 @@ ExampleCustomSearch.args = ExampleCustomSearchProps;
 
 export const ExampleCustomSearchWithLabel = Template.bind({});
 ExampleCustomSearchWithLabel.args = { ...ExampleCustomSearchProps, hasHiddenLabel: false };
+
+export const ExampleCustomSearchWithId = Template.bind({});
+ExampleCustomSearchWithId.args = { ...ExampleCustomSearchProps, id: 'myCustomId' };
```
Comment (chrisrhymes) [inline src/library/components/CustomSearch/CustomSearch.stories.tsx:31]: Example added demonstrating setting a custom id

File: src/library/components/CustomSearch/CustomSearch.tsx [hunk 3]
```diff
@@ -14,8 +14,8 @@ const CustomSearch: React.FunctionComponent<CustomSearchProps> = ({
   searchText,
   id,
 }) => {
-  if (id === null) {
-    id = uniqueID();
+  if (!id) {
+    id = useId();
```
Comment (chrisrhymes) [inline src/library/components/CustomSearch/CustomSearch.tsx:18]: Generate id when id is falsy, including undefined and also replace the uniqueID with the built in [React Hook](https://beta.reactjs.org/reference/react/useId).

**Review by DamienBurkeWN — APPROVED** [review]
👍
